import { config } from "dotenv";
import { defineConfig } from "drizzle-kit";

/**
 * Load Next.js-style env files. Drizzle Kit runs as a standalone CLI so it
 * doesn't pick up `.env.local` automatically the way `next dev` does.
 * Order matters — `.env.local` overrides `.env` to mirror Next.js precedence.
 */
config({ path: ".env" });
config({ path: ".env.local", override: true });

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set for drizzle-kit");
}

export default defineConfig({
  schema: "./src/lib/db/schema.ts",
  out: "./drizzle/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  schemaFilter: ["public"],
  /**
   * Use timestamp prefixes (YYYYMMDDHHMMSS_*) so files generated by
   * `db:generate` interleave correctly with hand-written SQL migrations
   * (RLS, triggers, etc) when our custom migrator sorts lexically.
   */
  migrations: {
    prefix: "timestamp",
    table: "_migrations",
    schema: "public",
  },
  verbose: true,
  strict: true,
});
